### ISSUE TITLE
Failed to update some plugins

### ISSUE THREAD

**Issue by amovsesy** [dpa99c/cordova-check-plugins#19] opened 2017-01-25 05:05 UTC
cordova-plugin-image-picker says it updates, but doesn't

====================================================================

Updating 'cordova-plugin-file'... -
Error removing plugin 'cordova-plugin-file'

Error: Command failed: cordova plugin rm cordova-plugin-file
Error: The plugin 'cordova-plugin-file' is required by (cordova-plugin-file-transfer, cordova-plugin-media-capture), skipping uninstallation. (try --force if trying to update)

Failed to update plugin 'cordova-plugin-file'

====================================================================

Updating 'cordova-plugin-compat'... \
Error removing plugin 'cordova-plugin-compat'

Error: Command failed: cordova plugin rm cordova-plugin-compat
Error: The plugin 'cordova-plugin-compat' is required by (cordova-plugin-file-transfer, cordova-plugin-media-capture, cordova-plugin-camera, cordova-plugin-contacts), skipping uninstallation. (try --force if trying to update)

Failed to update plugin 'cordova-plugin-compat'

**Comment by dpa99c** [comment] 2017-01-25 09:20
> cordova-plugin-image-picker says it updates, but doesn't

The console extract you've posted doesn't include `cordova-plugin-image-picker`, so this is not enough information.

Please run the `cordova-check-plugins` command with the `--verbose` option, then post:

- the full verbose console output
- the full list of command line arguments you're passing to `cordova-check-plugins`
- the contents of `plugins/fetch.json` in your Cordova project

**Comment by amovsesy** [comment] 2017-01-25 22:11
**> cordova-check-plugins --verbose**
Running cordova-check-plugins...
Verbose output enabled
Finding installed plugins
Reading installed plugin versions
Checking latest npm registry version for 'cordova-plugin-compat' using 'cordova-plugin-compat'
Checking latest npm registry version for 'cordova-plugin-file' using 'cordova-plugin-file'
Checking latest npm registry version for 'ionic-plugin-keyboard' using 'ionic-plugin-keyboard'
Checking latest npm registry version for 'cordova-plugin-ignore-lint-translation' using 'cordova-plugin-ignore-lint-translation'
Checking latest github version for 'com.wodify.cordova.plugin.instabug' using 'https://github.com/elizabethrego/cordova-plugin-instabug'
Checking latest github version for 'me.tonny.cordova.plugins.multidex' using 'https://github.com/jwall149/cordova-multidex'
Checking latest npm registry version for 'cordova-plugin-statusbar' using 'cordova-plugin-statusbar@2.2.0'
Checking latest npm registry version for 'cordova-plugin-whitelist' using 'cordova-plugin-whitelist@1.3.0'
Checking latest npm registry version for 'phonegap-plugin-push' using 'phonegap-plugin-push@1.8.4'
Checking latest npm registry version for 'es6-promise-plugin' using 'es6-promise-plugin'
Checking latest npm registry version for 'cordova-plugin-device' using 'cordova-plugin-device'
Checking latest npm registry version for 'cordova-universal-links-plugin' using 'cordova-universal-links-plugin'
Checking latest npm registry version for 'io.branch.sdk' using 'branch-cordova-sdk'
Checking latest npm registry version for 'cordova-sqlite-storage' using 'cordova-sqlite-storage@2.0.1'
Checking latest npm registry version for 'ionic-plugin-deeplinks' using 'ionic-plugin-deeplinks'
Checking latest npm registry version for 'cordova-plugin-file-transfer' using 'cordova-plugin-file-transfer'
Checking latest npm registry version for 'cordova-plugin-media-capture' using 'cordova-plugin-media-capture'
Checking latest npm registry version for 'cordova-fabric-plugin' using 'cordova-fabric-plugin'
Checking latest npm registry version for 'cordova-plugin-google-analytics' using 'cordova-plugin-google-analytics'
Checking latest npm registry version for 'cordova-plugin-image-picker' using 'cordova-plugin-image-picker'
Checking latest npm registry version for 'cordova-plugin-camera' using 'cordova-plugin-camera'
Checking latest npm registry version for 'cordova-plugin-contacts' using 'cordova-plugin-contacts'
Checking latest npm registry version for 'cordova-plugin-facebook4' using 'cordova-plugin-facebook4@~1.7.1'
Checking latest npm registry version for 'cordova-plugin-splashscreen' using 'cordova-plugin-splashscreen@4.0.1'
Checking latest npm registry version for 'cordova-plugin-inappbrowser' using 'cordova-plugin-inappbrowser@1.6.1'
Checking remote versions... -Retrieved latest github version for 'me.tonny.cordova.plugins.multidex
Checking remote versions... \Retrieved latest github version for 'com.wodify.cordova.plugin.instabug
Checking remote versions... -Retrieved latest npm registry version for 'cordova-plugin-compat
Checking remote versions... \Retrieved latest npm registry version for 'ionic-plugin-keyboard
Checking remote versions... |Retrieved latest npm registry version for 'cordova-plugin-whitelist
Checking remote versions... -Retrieved latest npm registry version for 'cordova-plugin-file
Checking remote versions... |Retrieved latest npm registry version for 'cordova-fabric-plugin
Retrieved latest npm registry version for 'es6-promise-plugin
Checking remote versions... /Retrieved latest npm registry version for 'cordova-plugin-statusbar
Checking remote versions... -Retrieved latest npm registry version for 'cordova-universal-links-plugin
Retrieved latest npm registry version for 'cordova-plugin-device
Checking remote versions... \Retrieved latest npm registry version for 'cordova-plugin-ignore-lint-translation
Checking remote versions... |Retrieved latest npm registry version for 'phonegap-plugin-push
Checking remote versions... /Retrieved latest npm registry version for 'io.branch.sdk
Retrieved latest npm registry version for 'cordova-plugin-inappbrowser
Retrieved latest npm registry version for 'cordova-sqlite-storage
Checking remote versions... -Retrieved latest npm registry version for 'cordova-plugin-image-picker
Checking remote versions... \Retrieved latest npm registry version for 'cordova-plugin-file-transfer
Retrieved latest npm registry version for 'cordova-plugin-google-analytics
Checking remote versions... |Retrieved latest npm registry version for 'cordova-plugin-media-capture
Retrieved latest npm registry version for 'cordova-plugin-contacts
Checking remote versions... /Retrieved latest npm registry version for 'cordova-plugin-splashscreen
Retrieved latest npm registry version for 'cordova-plugin-camera
Checking remote versions... |Retrieved latest npm registry version for 'ionic-plugin-deeplinks
Checking remote versions... /Retrieved latest npm registry version for 'cordova-plugin-facebook4

**********************
* Up-to-date plugins *
**********************

plugin: ionic-plugin-keyboard
source: npm://ionic-plugin-keyboard
installed version: 2.2.1
remote version: 2.2.1

plugin: cordova-plugin-ignore-lint-translation
source: npm://cordova-plugin-ignore-lint-translation
installed version: 0.0.1
remote version: 0.0.1

plugin: com.wodify.cordova.plugin.instabug
source: https://github.com/elizabethrego/cordova-plugin-instabug
installed version: 0.0.1
remote version: 0.0.1

plugin: me.tonny.cordova.plugins.multidex
source: https://github.com/jwall149/cordova-multidex
installed version: 0.1.0
remote version: 0.1.0

plugin: cordova-plugin-statusbar
source: npm://cordova-plugin-statusbar@2.2.0
installed version: 2.2.0
remote version: 2.2.0

plugin: cordova-plugin-whitelist
source: npm://cordova-plugin-whitelist@1.3.0
installed version: 1.3.0
remote version: 1.3.0

plugin: phonegap-plugin-push
source: npm://phonegap-plugin-push@1.8.4
installed version: 1.8.4
remote version: 1.8.4

plugin: es6-promise-plugin
source: npm://es6-promise-plugin
installed version: 3.0.2
remote version: 3.0.2

plugin: cordova-plugin-device
source: npm://cordova-plugin-device
installed version: 1.1.4
remote version: 1.1.4

plugin: cordova-universal-links-plugin
source: npm://cordova-universal-links-plugin
installed version: 1.2.1
remote version: 1.2.1

plugin: io.branch.sdk
source: npm://branch-cordova-sdk
installed version: 2.4.9
remote version: 2.4.9

plugin: cordova-sqlite-storage
source: npm://cordova-sqlite-storage@2.0.1
installed version: 2.0.1
remote version: 2.0.1

plugin: ionic-plugin-deeplinks
source: npm://ionic-plugin-deeplinks
installed version: 1.0.14
remote version: 1.0.14

plugin: cordova-plugin-file-transfer
source: npm://cordova-plugin-file-transfer
installed version: 1.6.1
remote version: 1.6.1

plugin: cordova-plugin-media-capture
source: npm://cordova-plugin-media-capture
installed version: 1.4.1
remote version: 1.4.1

plugin: cordova-fabric-plugin
source: npm://cordova-fabric-plugin
installed version: 1.1.3
remote version: 1.1.3

plugin: cordova-plugin-google-analytics
source: npm://cordova-plugin-google-analytics
installed version: 1.7.4
remote version: 1.7.4

plugin: cordova-plugin-camera
source: npm://cordova-plugin-camera
installed version: 2.3.1
remote version: 2.3.1

plugin: cordova-plugin-contacts
source: npm://cordova-plugin-contacts
installed version: 2.2.1
remote version: 2.2.1

plugin: cordova-plugin-facebook4
source: npm://cordova-plugin-facebook4@~1.7.1
installed version: 1.7.4
remote version: 1.7.4

plugin: cordova-plugin-splashscreen
source: npm://cordova-plugin-splashscreen@4.0.1
installed version: 4.0.1
remote version: 4.0.1

plugin: cordova-plugin-inappbrowser
source: npm://cordova-plugin-inappbrowser@1.6.1
installed version: 1.6.1
remote version: 1.6.1


***************************
* Plugin update available *
***************************

plugin: cordova-plugin-compat
source: npm://cordova-plugin-compat
installed version: 1.0.0
remote version: 1.1.0

plugin: cordova-plugin-file
source: npm://cordova-plugin-file
installed version: 4.2.0
remote version: 4.3.1

plugin: cordova-plugin-image-picker
source: npm://cordova-plugin-image-picker
installed version: 1.1.1
remote version: 1.1.3



**cordova-check-plugins --update=auto --verbose**
Running cordova-check-plugins...
Verbose output enabled
Finding installed plugins
Reading installed plugin versions
Checking latest npm registry version for 'cordova-plugin-compat' using 'cordova-plugin-compat'
Checking latest npm registry version for 'cordova-plugin-file' using 'cordova-plugin-file'
Checking latest npm registry version for 'ionic-plugin-keyboard' using 'ionic-plugin-keyboard'
Checking latest npm registry version for 'cordova-plugin-ignore-lint-translation' using 'cordova-plugin-ignore-lint-translation'
Checking latest github version for 'com.wodify.cordova.plugin.instabug' using 'https://github.com/elizabethrego/cordova-plugin-instabug'
Checking latest github version for 'me.tonny.cordova.plugins.multidex' using 'https://github.com/jwall149/cordova-multidex'
Checking latest npm registry version for 'cordova-plugin-statusbar' using 'cordova-plugin-statusbar@2.2.0'
Checking latest npm registry version for 'cordova-plugin-whitelist' using 'cordova-plugin-whitelist@1.3.0'
Checking latest npm registry version for 'phonegap-plugin-push' using 'phonegap-plugin-push@1.8.4'
Checking latest npm registry version for 'es6-promise-plugin' using 'es6-promise-plugin'
Checking latest npm registry version for 'cordova-plugin-device' using 'cordova-plugin-device'
Checking latest npm registry version for 'cordova-universal-links-plugin' using 'cordova-universal-links-plugin'
Checking latest npm registry version for 'io.branch.sdk' using 'branch-cordova-sdk'
Checking latest npm registry version for 'cordova-sqlite-storage' using 'cordova-sqlite-storage@2.0.1'
Checking latest npm registry version for 'ionic-plugin-deeplinks' using 'ionic-plugin-deeplinks'
Checking latest npm registry version for 'cordova-plugin-file-transfer' using 'cordova-plugin-file-transfer'
Checking latest npm registry version for 'cordova-plugin-media-capture' using 'cordova-plugin-media-capture'
Checking latest npm registry version for 'cordova-fabric-plugin' using 'cordova-fabric-plugin'
Checking latest npm registry version for 'cordova-plugin-google-analytics' using 'cordova-plugin-google-analytics'
Checking latest npm registry version for 'cordova-plugin-image-picker' using 'cordova-plugin-image-picker'
Checking latest npm registry version for 'cordova-plugin-camera' using 'cordova-plugin-camera'
Checking latest npm registry version for 'cordova-plugin-contacts' using 'cordova-plugin-contacts'
Checking latest npm registry version for 'cordova-plugin-facebook4' using 'cordova-plugin-facebook4@~1.7.1'
Checking latest npm registry version for 'cordova-plugin-splashscreen' using 'cordova-plugin-splashscreen@4.0.1'
Checking latest npm registry version for 'cordova-plugin-inappbrowser' using 'cordova-plugin-inappbrowser@1.6.1'
Checking remote versions... /Retrieved latest github version for 'com.wodify.cordova.plugin.instabug
Retrieved latest github version for 'me.tonny.cordova.plugins.multidex
Checking remote versions... \Retrieved latest npm registry version for 'cordova-plugin-compat
Checking remote versions... |Retrieved latest npm registry version for 'cordova-plugin-file
Retrieved latest npm registry version for 'cordova-plugin-whitelist
Checking remote versions... /Retrieved latest npm registry version for 'ionic-plugin-keyboard
Retrieved latest npm registry version for 'cordova-universal-links-plugin
Retrieved latest npm registry version for 'es6-promise-plugin
Retrieved latest npm registry version for 'cordova-fabric-plugin
Checking remote versions... \Retrieved latest npm registry version for 'ionic-plugin-deeplinks
Retrieved latest npm registry version for 'cordova-plugin-device
Retrieved latest npm registry version for 'cordova-plugin-google-analytics
Retrieved latest npm registry version for 'cordova-plugin-ignore-lint-translation
Checking remote versions... |Retrieved latest npm registry version for 'cordova-plugin-statusbar
Retrieved latest npm registry version for 'io.branch.sdk
Checking remote versions... /Retrieved latest npm registry version for 'cordova-plugin-inappbrowser
Retrieved latest npm registry version for 'cordova-plugin-splashscreen
Retrieved latest npm registry version for 'cordova-plugin-file-transfer
Checking remote versions... -Retrieved latest npm registry version for 'cordova-plugin-media-capture
Retrieved latest npm registry version for 'cordova-plugin-facebook4
Retrieved latest npm registry version for 'phonegap-plugin-push
Checking remote versions... \Retrieved latest npm registry version for 'cordova-sqlite-storage
Retrieved latest npm registry version for 'cordova-plugin-camera
Retrieved latest npm registry version for 'cordova-plugin-contacts
Checking remote versions... -Retrieved latest npm registry version for 'cordova-plugin-image-picker

**********************
* Up-to-date plugins *
**********************

plugin: ionic-plugin-keyboard
source: npm://ionic-plugin-keyboard
installed version: 2.2.1
remote version: 2.2.1

plugin: cordova-plugin-ignore-lint-translation
source: npm://cordova-plugin-ignore-lint-translation
installed version: 0.0.1
remote version: 0.0.1

plugin: com.wodify.cordova.plugin.instabug
source: https://github.com/elizabethrego/cordova-plugin-instabug
installed version: 0.0.1
remote version: 0.0.1

plugin: me.tonny.cordova.plugins.multidex
source: https://github.com/jwall149/cordova-multidex
installed version: 0.1.0
remote version: 0.1.0

plugin: cordova-plugin-statusbar
source: npm://cordova-plugin-statusbar@2.2.0
installed version: 2.2.0
remote version: 2.2.0

plugin: cordova-plugin-whitelist
source: npm://cordova-plugin-whitelist@1.3.0
installed version: 1.3.0
remote version: 1.3.0

plugin: phonegap-plugin-push
source: npm://phonegap-plugin-push@1.8.4
installed version: 1.8.4
remote version: 1.8.4

plugin: es6-promise-plugin
source: npm://es6-promise-plugin
installed version: 3.0.2
remote version: 3.0.2

plugin: cordova-plugin-device
source: npm://cordova-plugin-device
installed version: 1.1.4
remote version: 1.1.4

plugin: cordova-universal-links-plugin
source: npm://cordova-universal-links-plugin
installed version: 1.2.1
remote version: 1.2.1

plugin: io.branch.sdk
source: npm://branch-cordova-sdk
installed version: 2.4.9
remote version: 2.4.9

plugin: cordova-sqlite-storage
source: npm://cordova-sqlite-storage@2.0.1
installed version: 2.0.1
remote version: 2.0.1

plugin: ionic-plugin-deeplinks
source: npm://ionic-plugin-deeplinks
installed version: 1.0.14
remote version: 1.0.14

plugin: cordova-plugin-file-transfer
source: npm://cordova-plugin-file-transfer
installed version: 1.6.1
remote version: 1.6.1

plugin: cordova-plugin-media-capture
source: npm://cordova-plugin-media-capture
installed version: 1.4.1
remote version: 1.4.1

plugin: cordova-fabric-plugin
source: npm://cordova-fabric-plugin
installed version: 1.1.3
remote version: 1.1.3

plugin: cordova-plugin-google-analytics
source: npm://cordova-plugin-google-analytics
installed version: 1.7.4
remote version: 1.7.4

plugin: cordova-plugin-camera
source: npm://cordova-plugin-camera
installed version: 2.3.1
remote version: 2.3.1

plugin: cordova-plugin-contacts
source: npm://cordova-plugin-contacts
installed version: 2.2.1
remote version: 2.2.1

plugin: cordova-plugin-facebook4
source: npm://cordova-plugin-facebook4@~1.7.1
installed version: 1.7.4
remote version: 1.7.4

plugin: cordova-plugin-splashscreen
source: npm://cordova-plugin-splashscreen@4.0.1
installed version: 4.0.1
remote version: 4.0.1

plugin: cordova-plugin-inappbrowser
source: npm://cordova-plugin-inappbrowser@1.6.1
installed version: 1.6.1
remote version: 1.6.1


***************************
* Plugin update available *
***************************

plugin: cordova-plugin-compat
source: npm://cordova-plugin-compat
installed version: 1.0.0
remote version: 1.1.0

plugin: cordova-plugin-file
source: npm://cordova-plugin-file
installed version: 4.2.0
remote version: 4.3.1

plugin: cordova-plugin-image-picker
source: npm://cordova-plugin-image-picker
installed version: 1.1.1
remote version: 1.1.3

Updating plugins: cordova-plugin-compat, cordova-plugin-file, cordova-plugin-image-picker


Updating 'cordova-plugin-image-picker'... \Removed plugin 'cordova-plugin-image-picker'
Update command: cordova plugin add cordova-plugin-image-picker --variable PHOTO_LIBRARY_USAGE_DESCRIPTION="Used to grab images when reporting an issue"
Updating 'cordova-plugin-image-picker'... -Re-added plugin 'cordova-plugin-image-picker'

Updated 'cordova-plugin-image-picker' from 1.1.1 to 1.1.3


Updating 'cordova-plugin-file'... \
Error removing plugin 'cordova-plugin-file'

Error: Command failed: cordova plugin rm cordova-plugin-file
Error: The plugin 'cordova-plugin-file' is required by (cordova-plugin-file-transfer, cordova-plugin-media-capture), skipping uninstallation. (try --force if trying to update)

Failed to update plugin 'cordova-plugin-file'


Updating 'cordova-plugin-compat'... \
Error removing plugin 'cordova-plugin-compat'

Error: Command failed: cordova plugin rm cordova-plugin-compat
Error: The plugin 'cordova-plugin-compat' is required by (cordova-plugin-file-transfer, cordova-plugin-media-capture, cordova-plugin-camera, cordova-plugin-contacts), skipping uninstallation. (try --force if trying to update)

Failed to update plugin 'cordova-plugin-compat'

Failed to update all outdated plugins


**plugins/fetch.json**
{
    "cordova-plugin-compat": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-compat"
        },
        "is_top_level": false,
        "variables": {}
    },
    "cordova-plugin-file": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-file"
        },
        "is_top_level": false,
        "variables": {}
    },
    "ionic-plugin-keyboard": {
        "source": {
            "type": "registry",
            "id": "ionic-plugin-keyboard"
        },
        "is_top_level": true,
        "variables": {}
    },
    "cordova-plugin-ignore-lint-translation": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-ignore-lint-translation"
        },
        "is_top_level": true,
        "variables": {}
    },
    "com.wodify.cordova.plugin.instabug": {
        "source": {
            "type": "git",
            "url": "https://github.com/elizabethrego/cordova-plugin-instabug",
            "subdir": "."
        },
        "is_top_level": true,
        "variables": {}
    },
    "me.tonny.cordova.plugins.multidex": {
        "source": {
            "type": "git",
            "url": "https://github.com/jwall149/cordova-multidex",
            "subdir": "."
        },
        "is_top_level": false,
        "variables": {}
    },
    "cordova-plugin-statusbar": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-statusbar@2.2.0"
        },
        "is_top_level": true,
        "variables": {}
    },
    "cordova-plugin-whitelist": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-whitelist@1.3.0"
        },
        "is_top_level": true,
        "variables": {}
    },
    "phonegap-plugin-push": {
        "source": {
            "type": "registry",
            "id": "phonegap-plugin-push@1.8.4"
        },
        "is_top_level": true,
        "variables": {
            "SENDER_ID": "108311884083"
        }
    },
    "es6-promise-plugin": {
        "source": {
            "type": "registry",
            "id": "es6-promise-plugin"
        },
        "is_top_level": false,
        "variables": {}
    },
    "cordova-plugin-device": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-device"
        },
        "is_top_level": true,
        "variables": {}
    },
    "cordova-universal-links-plugin": {
        "source": {
            "type": "registry",
            "id": "cordova-universal-links-plugin"
        },
        "is_top_level": true,
        "variables": {}
    },
    "io.branch.sdk": {
        "source": {
            "type": "registry",
            "id": "branch-cordova-sdk"
        },
        "is_top_level": true,
        "variables": {
            "BRANCH_KEY": "key_live_fmAdGtVHEr4FvV6a2C6K4nkaxDnbt51O",
            "URI_SCHEME": "zently"
        }
    },
    "cordova-sqlite-storage": {
        "source": {
            "type": "registry",
            "id": "cordova-sqlite-storage@2.0.1"
        },
        "is_top_level": true,
        "variables": {}
    },
    "ionic-plugin-deeplinks": {
        "source": {
            "type": "registry",
            "id": "ionic-plugin-deeplinks"
        },
        "is_top_level": true,
        "variables": {
            "URL_SCHEME": "zently",
            "DEEPLINK_SCHEME": "https",
            "DEEPLINK_HOST": "www.zently.co"
        }
    },
    "cordova-plugin-file-transfer": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-file-transfer"
        },
        "is_top_level": true,
        "variables": {}
    },
    "cordova-plugin-media-capture": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-media-capture"
        },
        "is_top_level": true,
        "variables": {
            "CAMERA_USAGE_DESCRIPTION": "Used to get images when reporting issues",
            "MICROPHONE_USAGE_DESCRIPTION": "Not used",
            "PHOTOLIBRARY_USAGE_DESCRIPTION": "Get pictures for issues from photo library"
        }
    },
    "cordova-fabric-plugin": {
        "source": {
            "type": "registry",
            "id": "cordova-fabric-plugin"
        },
        "is_top_level": true,
        "variables": {
            "FABRIC_API_KEY": "6402c498787c391ebba4baa100ea44c3d0787486",
            "FABRIC_API_SECRET": "f39b8aef1c9a04a810edd4f6a0837080aa65a509cb68bb873f802ebd1e8e1455"
        }
    },
    "cordova-plugin-google-analytics": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-google-analytics"
        },
        "is_top_level": true,
        "variables": {}
    },
    "cordova-plugin-camera": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-camera"
        },
        "is_top_level": true,
        "variables": {
            "CAMERA_USAGE_DESCRIPTION": "Take pictures of issues",
            "PHOTOLIBRARY_USAGE_DESCRIPTION": "Grab images of issues already stored on your phone"
        }
    },
    "cordova-plugin-contacts": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-contacts"
        },
        "is_top_level": true,
        "variables": {
            "CONTACTS_USAGE_DESCRIPTION": "Easily add your landlord and roomates"
        }
    },
    "cordova-plugin-facebook4": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-facebook4@~1.7.1"
        },
        "is_top_level": true,
        "variables": {
            "APP_ID": "110917049347751",
            "APP_NAME": "Zently"
        }
    },
    "cordova-plugin-splashscreen": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-splashscreen@4.0.1"
        },
        "is_top_level": true,
        "variables": {}
    },
    "cordova-plugin-inappbrowser": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-inappbrowser@1.6.1"
        },
        "is_top_level": true,
        "variables": {}
    },
    "cordova-plugin-image-picker": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-image-picker"
        },
        "is_top_level": true,
        "variables": {
            "PHOTO_LIBRARY_USAGE_DESCRIPTION": "Used to grab images when reporting an issue"
        }
    }
}

**Comment by dpa99c** [comment] 2017-01-26 19:30
`--update=auto` output says:

    Updated 'cordova-plugin-image-picker' from 1.1.1 to 1.1.3

So what version does it show if you do `cordova plugin ls` ?

BTW the plugins that failed are ones that others are dependent on but can be updated by add the `--force` argument.

**Comment by amovsesy** [comment] 2017-01-27 00:29
cordova-plugin-image-picker 1.1.1 "ImagePicker"

I tried doing it manually as well and the same thing happens so I don't think it is your code, but rather something with them.

**Comment by dpa99c** [comment] 2017-01-27 08:14
The issue is with `cordova-plugin-image-picker`

While they have bumped the [version in package.json](https://github.com/wymsee/cordova-imagePicker/blob/master/package.json#L3) to `1.1.3` they have not bumped the [version in plugin.xml](https://github.com/wymsee/cordova-imagePicker/blob/master/plugin.xml#L5), which is where Cordova  reads the version from. So if you look in your local `plugins/cordova-plugin-image-picker` you'll see this is the case.

So the plugin code you've got is `1.1.3` but it's being listed as `1.1.1` by Cordova.

You could open an issue/pull request on their Github page, but give the number that are open, it doesn't look like it will be fixed any time soon.

Maybe better to install the [Telerik fork](https://github.com/Telerik-Verified-Plugins/ImagePicker) direct from Github - it seems better maintained.

Closing this issue as the problem is not with `cordova-check-plugins`

**Closed by dpa99c** 2017-01-27 08:14 UTC
Labels: more info needed
